n = int(input())
set1 = set(input().split())
N = int(input())
set2 = set(input().split())
intersectionSET = (set1&set2)
unionSET = (set1|set2)
diffSET = (set1-set2)
symmetricdiffSET = (set1^set2)
print(len(intersectionSET), len(unionSET))